### ISSUE TITLE
Yarn install warnings

### ISSUE THREAD

**Issue by nemanjam** [jellydn/next-validations#193]
Hello. How can these warnings be avoided during yarn install?

![2021-12-30_13-18](https://user-images.githubusercontent.com/9990165/147752297-6e68f7fd-55f0-479d-b53a-a2c935f175dd.png)

**Comment by jellydn** [comment]
Thanks @nemanjam Fixed by v0.1.11

```
 next-validations 0.1.11 published 🎉
```

**Comment by nemanjam** [comment]
Thank you.
