### ISSUE TITLE
Feature Request: Validation of multiple modes at the same time

### ISSUE THREAD

**Issue by netoht** [jellydn/next-validations#558]
**Describe The Problem**

I am developing an application with nextjs and I must apply some validations in query and body to enforce the correct data type with the method `withValidation`, but this method accepts only one mode validation at the same time.

To clarify my specific scenario are:

In query mode validation I must check if the `collectionId` and `tokenId` are numeric `http://localhost:3000/api/v1/[collectionId]/[tokenId]/metadata`

And in the body mode validation, I must check if the payload contains in JSON an attribute called attributes.

Do you have the intention to evolve this project to cover this scenario?

**Comment by jellydn** [comment]
Hi @netoht 
Thanks you for opening this issue. 

Technically, I think we could expand the API on this package to support array. Something like this.

```typescript
const querySchema = {
  schema: {}, // validate the query params
  type: 'Yup',
  mode: 'query',
}

const bodySchema = {
  schema: {}, // validate body param
  type: 'Yup',
  mode: 'body',
}

const validate = withValidations([querySchema,bodySchema]);

```

>Do you have the intention to evolve this project to cover this scenario?

I'm quite busy however I will give it a try when I'm available.

**Comment by jellydn** [comment]
Hello @netoht I've just publish the version. Please take a try and let me know if you have any issue.

```
 next-validations 0.3.0-0 published 🎉
```

Usage: https://github.com/jellydn/next-validations/blob/937dee6fb4c280ab525040faf62f0632ac1c691f/example/pages/api/support.ts

**Comment by netoht** [comment]
@jellydn Awesome! Thank you for your agility to deliver

**Comment by jellydn** [comment]
> @jellydn Awesome! Thank you for your agility to deliver it
You're welcome :)  You could support this project by ⭐️ starring and sharing it. [Follow me](https://github.com/jellydn) to see what other cool projects I'm working on! ❤️ Thanks.
