### ISSUE TITLE
ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING_FLAG

### ISSUE THREAD

**Issue by matapo** [jellydn/next-validations#959]
### Details

We are using Zod and upgrading "next-validations": "0.4.2" -> to "1.0.2" leads to an error during testing (jest) phase. Is there a missing step in configuration? 

node v21.5.0

```
    expect(received).toMatchObject(expected)

    - Expected  - 1
    + Received  + 1

      Object {
    -   "error": "invalid login_hint provided",
    +   "code": "ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING_FLAG",
      }

      634 |       .expect(400)
      635 |       .expect("Content-Type", /json/);
    > 636 |     expect(result.body).toMatchObject({
          |                         ^
      637 |       error: "invalid login_hint provided",
      638 |     });
      639 |   });

```

**Comment by jellydn** [comment]
Hi @matapo Thank you for your report. This is new to me as well. Let me check and get back to you sometime this week.

**Comment by jellydn** [comment]
FYI - It sounds like a issue with nextjs https://github.com/vercel/next.js/issues/34685
